baseURL: "/"
title: "Omalogisch"
languageCode: "de"

# Enable Google Analytics by inserting your tracking code
googleAnalytics: ""

taxonomies:
  tag: "tags"
  category: "categories"
  rezept: "rezepte"
