baseURL: "/"
title: "natur zum anbeissen"
languageCode: "de"

# Enable Google Analytics by inserting your tracking code
googleAnalytics: "UA-98285979-1"

taxonomies:
  tag: "tags"
  category: "categories"
  rezept: "rezepte"
